# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "file://../packer_virtualbox-iso_virtualbox.box"
  config.vm.box_check_update = false

  config.vm.network "private_network", ip: "192.168.56.101", nic_type: "virtio", auto_config: false

  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.synced_folder "./", "/home/docker/sync", id: "docker", :nfs => true,  :mount_options   => ['nolock,vers=3,udp']


  config.vm.provider "virtualbox" do |vb|
    vb.name = "vagrant_boot2docker_ansible"
    vb.gui = true
    vb.memory = "512"
    vb.cpus = 2
  end
  
  config.ssh.username="docker"
  config.ssh.password="tcuser"
  config.ssh.shell="/bin/sh -l"

  config.vm.provision "shell", privileged: false, inline: <<-SHELL

    tce-load -wi python.tcz
    tce-load -wi python-setuptools.tcz
    tce-load -wi gcc.tcz
    tce-load -wi python-dev.tcz
    tce-load -wi linux-kernel-sources-env.tcz
    tce-load -wi gmp-dev.tcz
    tce-load -wi mc
    sleep 5
    wget http://releases.ansible.com/ansible/ansible-latest.tar.gz
    tar -xzvf ansible-latest.tar.gz
    cd ansible-*/
    python setup.py build
    sudo python setup.py install
    cd ..
    sudo rm -rf ansible-*
    echo "ANSIBLE INSTALLATION FINISHED"
    echo "Check the version:"
    ansible --version
    
  SHELL
end
